<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-J15UI2E7" failures="8" tests="8" name="SampleTest" time="92.579" errors="0" timestamp="2022-03-08T22:09:44 IST">
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="newTest" time="2.477">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/dashboard&amp;quot;
 but was: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "https://opensource-demo.orangehrmlive.com/index.php/dashboard"
 but was: "https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials"
at com.tmb.tests.OrangeHRMTests.newTest(OrangeHRMTests.java:47)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- newTest -->
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="test" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.tmb.tests.OrangeHRMTests.test(OrangeHRMTests.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="newTest" time="2.196">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/dashboard&amp;quot;
 but was: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "https://opensource-demo.orangehrmlive.com/index.php/dashboard"
 but was: "https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials"
at com.tmb.tests.OrangeHRMTests.newTest(OrangeHRMTests.java:47)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- newTest -->
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="validateLoginLogout" time="2.162">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/dashboard&amp;quot;
 but was: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "https://opensource-demo.orangehrmlive.com/index.php/dashboard"
 but was: "https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials"
at com.tmb.tests.OrangeHRMTests.validateLoginLogout(OrangeHRMTests.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginLogout -->
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="newTest" time="2.243">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/dashboard&amp;quot;
 but was: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "https://opensource-demo.orangehrmlive.com/index.php/dashboard"
 but was: "https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials"
at com.tmb.tests.OrangeHRMTests.newTest(OrangeHRMTests.java:47)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- newTest -->
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="validateLoginLogout" time="1.93">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/dashboard&amp;quot;
 but was: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "https://opensource-demo.orangehrmlive.com/index.php/dashboard"
 but was: "https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials"
at com.tmb.tests.OrangeHRMTests.validateLoginLogout(OrangeHRMTests.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginLogout -->
  <testcase classname="com.tmb.tests.OrangeHRMTests" name="validateLoginLogout" time="1.855">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/dashboard&amp;quot;
 but was: &amp;quot;https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "https://opensource-demo.orangehrmlive.com/index.php/dashboard"
 but was: "https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials"
at com.tmb.tests.OrangeHRMTests.validateLoginLogout(OrangeHRMTests.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginLogout -->
  <testcase classname="com.tmb.tests.AmazonTests" name="demoAmazonTest" time="15.522">
    <failure type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for element to be clickable: By.xpath: //a[@id=&amp;apos;nav-hamburger-menu&amp;apos;] (tried for 15 second(s) with 500 milliseconds interval)
Build info: version: &amp;apos;4.1.2&amp;apos;, revision: &amp;apos;9a5a329c5a&amp;apos;
System info: host: &amp;apos;LAPTOP-J15UI2E7&amp;apos;, ip: &amp;apos;192.168.0.111&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;16.0.1&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 97.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20220304162637, moz:debuggerAddress: localhost:49629, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 23412, moz:profile: C:\Users\shara\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:49629/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 943ac426-9d0e-4773-8c9e-f2a4c842e785">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //a[@id='nav-hamburger-menu'] (tried for 15 second(s) with 500 milliseconds interval)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'LAPTOP-J15UI2E7', ip: '192.168.0.111', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 97.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20220304162637, moz:debuggerAddress: localhost:49629, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 23412, moz:profile: C:\Users\shara\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:49629/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 943ac426-9d0e-4773-8c9e-f2a4c842e785
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:138)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at com.tmb.factories.ExplicitWaitFactory.performExplicitWait(ExplicitWaitFactory.java:22)
at com.tmb.pages.BasePage.doClick(BasePage.java:29)
at com.tmb.pages.AmazonHomePage.clickHamburgerMenu(AmazonHomePage.java:13)
at com.tmb.tests.AmazonTests.demoAmazonTest(AmazonTests.java:23)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- demoAmazonTest -->
</testsuite> <!-- SampleTest -->
