<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-J15UI2E7" failures="1" tests="5" name="SuiteTestListeners" time="0.077" errors="0" timestamp="2022-03-03T10:28:08 IST">
  <testcase classname="testnglistenershandson.Runner" name="test2" time="0.01">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testnglistenershandson.Runner" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testnglistenershandson.Runner" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testnglistenershandson.Runner.test2(Runner.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testnglistenershandson.Runner" name="test3" time="0.001"/>
  <testcase classname="testnglistenershandson.Runner" name="test3" time="0.001"/>
  <testcase classname="testnglistenershandson.Runner" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- SuiteTestListeners -->
